---
title: "Dicamba 2019"
author: "Maxwel Coura Oliveira"
date: "8/6/2019"
output: pdf_document
---


```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(drc)
```




```{r}
Data <- read_csv("Dicamba.csv") 
glimpse(Data)
```


```{r}
ggplot(Data, aes(x=Distancem, y=Injury)) + geom_smooth(method = "loess") + facet_grid(Type~Location) + theme_bw() +
  labs(x="Distance (m)", y="Non-DT soybean injury (%)") +
  ggsave("Dicamba19.png", height = 6, width=10, dpi=300)
```


```{r}
No <- Data %>% 
  filter(Location == "N")

N <- drm(Injury ~ Distancem, Type, fct = l3(), data=No)
summary(N)
plot(N)
```



```{r include=FALSE, warning = FALSE}
newdata <- expand.grid(Distancem=exp(seq(log(0.5), log(60), length=60)))



newdata1 <- data.frame(Type ="Covered", newdata) 
newdata2 <- data.frame(Type ="Non-Covered", newdata)



nd=rbind(newdata1, newdata2)


#options(error=function() dump.frames(to.file=TRUE))

pm <- predict(N, newdata=nd, interval="confidence")







nd$p <- pm[,1] 
nd$pmin <- pm[,2]   
nd$pmax <- pm[,3] 


No$Distancem0 <- No$Distancem 
No$Distancem0[No$h0==0] <- 0.5 
```

```{r}
p1<-ggplot(No, aes(x = Distancem0, y = Injury, color=Type, fill=Type, linetype=Type)) +  theme_bw() + 
  geom_line(data=nd, aes(x=Distancem, y=p, color=Type, fill=Type, linetype=Type), size=1.3) + #coord_trans(x="log") + 
  geom_ribbon(data=nd, aes(Distancem, y=p, ymin=pmin, ymax=pmax, fill=Type), alpha=0.2, color=NA) +
  labs(y="Non-DR soybean injury (%)", x="Distance (m)", caption = "") +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_manual(values = c("black", "red")) +
  scale_linetype_manual(values=c("dotdash", "solid")) +
    ylim(-5,100) +
  annotate("text", x = 60, y = 100, label = c("North"), size=5, face="bold") +
  theme(legend.position=c(0.2, 0.9), panel.grid = element_blank(), axis.title = element_text(size=15, color = "black"), legend.title = element_blank(), legend.text = element_text(size=13), axis.text = element_text(size=14, color = "black")) +
  scale_x_continuous(breaks=c(0, 10, 20, 30, 40, 50,60, 70)) +
  ggsave("North.png", height = 6, width = 6, dpi=300)
```


```{r}
Ea<- Data %>% 
  filter(Location == "E")

E <- drm(Injury ~ Distancem, Type, fct = l3(), data=Ea)
summary(E)
plot(E)
```


```{r include=FALSE, warning = FALSE}
newdata <- expand.grid(Distancem=exp(seq(log(0.5), log(42), length=42)))

newdata1 <- data.frame(Type ="Covered", newdata) 
newdata2 <- data.frame(Type ="Non-Covered", newdata)



nd=rbind(newdata1, newdata2)



pm <- predict(E, newdata=nd, interval="confidence")







nd$p <- pm[,1] 
nd$pmin <- pm[,2]   
nd$pmax <- pm[,3] 


Ea$Distancem0 <- Ea$Distancem 
Ea$Distancem0[Ea$h0==0] <- 0.5 
```



```{r warning=FALSE, echo=FALSE, fig.height= 6, fig.width=6, fig.cap="Non-Xtend soybean injury (%) with distance (m) from the dicamba treated area (Yes or No Type) at 21 DAT in Indiana."}
p2<-ggplot(Ea, aes(x = Distancem0, y = Injury, color=Type, fill=Type, linetype=Type)) +  theme_bw() + #geom_point(aes(shape=Type)) +
  geom_line(data=nd, aes(x=Distancem, y=p, color=Type, fill=Type, linetype=Type), size=1.3) + #coord_trans(x="log") + 
  geom_ribbon(data=nd, aes(Distancem, y=p, ymin=pmin, ymax=pmax, fill=Type), alpha=0.2, color=NA) +
  labs(y="Non-DR soybean injury (%)", x="Distance (m)", caption = "") +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_manual(values = c("black", "red")) +
    scale_linetype_manual(values=c("dotdash", "solid")) +
    annotate("text", x = 42, y = 100, label = c("East"), size=5) +
    ylim(-5,100) +
  theme(legend.position="none", panel.grid = element_blank(), axis.title = element_text(size=15, color = "black"), axis.text = element_text(size=14, color = "black")) +
  scale_x_continuous(breaks=c(0, 10, 20, 30, 40, 50)) +
  ggsave("East.png", height = 6, width = 6, dpi=300)
```



```{r}
We<- Data %>% 
  filter(Location == "W" | Row != 1)

W <- drm(Injury ~ Distancem, Type, fct = l3(), data=We)
summary(W)
plot(W)
```


```{r include=FALSE, warning = FALSE}
newdata <- expand.grid(Distancem=exp(seq(log(0.5), log(46), length=46)))

newdata1 <- data.frame(Type ="Covered", newdata) 
newdata2 <- data.frame(Type ="Non-Covered", newdata)



nd=rbind(newdata1, newdata2)



pm <- predict(W, newdata=nd, interval="confidence")







nd$p <- pm[,1] 
nd$pmin <- pm[,2]   
nd$pmax <- pm[,3] 


We$Distancem0 <- We$Distancem 
We$Distancem0[We$h0==0] <- 0.5 
```



```{r warning=FALSE, echo=FALSE, fig.height= 6, fig.width=6, fig.cap="Non-Xtend soybean injury (%) with distance (m) from the dicamba treated area (Yes or No Type) at 21 DAT in Indiana."}
p3<-ggplot(Ea, aes(x = Distancem0, y = Injury, color=Type, fill=Type, linetype=Type)) +  theme_bw() + #geom_point(aes(shape=Type)) +
  geom_line(data=nd, aes(x=Distancem, y=p, color=Type, fill=Type, linetype=Type), size=1.3) + #coord_trans(x="log") + 
  geom_ribbon(data=nd, aes(Distancem, y=p, ymin=pmin, ymax=pmax, fill=Type), alpha=0.2, color=NA) +
  labs(y="Non-DR soybean injury (%)", x="Distance (m)", caption = "") +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_manual(values = c("black", "red")) +
    scale_linetype_manual(values=c("dotdash", "solid")) +
    annotate("text", x = 42, y = 100, label = c("East"), size=5) +
    ylim(-5,100) +
  theme(legend.position="none", panel.grid = element_blank(), axis.title = element_text(size=15, color = "black"), axis.text = element_text(size=14, color = "black")) +
  scale_x_continuous(breaks=c(0, 10, 20, 30, 40, 50)) +
  ggsave("West.png", height = 6, width = 6, dpi=300)
```





```{r}
So<- Data %>% 
  filter(Location == "S" & Row != 1)

S <- drm(Injury ~ Distancem, Type, fct = l3(), data=So)
summary(S)
plot(S)
```


```{r include=FALSE, warning = FALSE}
newdata <- expand.grid(Distancem=exp(seq(log(0.5), log(46), length=46)))

newdata1 <- data.frame(Type ="Covered", newdata) 
newdata2 <- data.frame(Type ="Non-Covered", newdata)



nd=rbind(newdata1, newdata2)



pm <- predict(W, newdata=nd, interval="confidence")







nd$p <- pm[,1] 
nd$pmin <- pm[,2]   
nd$pmax <- pm[,3] 


So$Distancem0 <- So$Distancem 
So$Distancem0[So$h0==0] <- 0.5 
```



```{r warning=FALSE, echo=FALSE, fig.height= 6, fig.width=6, fig.cap="Non-Xtend soybean injury (%) with distance (m) from the dicamba treated area (Yes or No Type) at 21 DAT in Indiana."}
p3<-ggplot(Ea, aes(x = Distancem0, y = Injury, color=Type, fill=Type, linetype=Type)) +  theme_bw() + #geom_point(aes(shape=Type)) +
  geom_line(data=nd, aes(x=Distancem, y=p, color=Type, fill=Type, linetype=Type), size=1.3) + #coord_trans(x="log") + 
  geom_ribbon(data=nd, aes(Distancem, y=p, ymin=pmin, ymax=pmax, fill=Type), alpha=0.2, color=NA) +
  labs(y="Non-DR soybean injury (%)", x="Distance (m)", caption = "") +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_manual(values = c("black", "red")) +
    scale_linetype_manual(values=c("dotdash", "solid")) +
    annotate("text", x = 42, y = 100, label = c("East"), size=5) +
    ylim(-5,100) +
  theme(legend.position="none", panel.grid = element_blank(), axis.title = element_text(size=15, color = "black"), axis.text = element_text(size=14, color = "black")) +
  scale_x_continuous(breaks=c(0, 10, 20, 30, 40, 50)) +
  ggsave("West.png", height = 6, width = 6, dpi=300)
```