---
title: "Wind"
author: "Maxwel Coura Oliveira"
date: "8/22/2019"
output: pdf_document
---

```{r}
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
library(CircStats)
library(openair)
library(scales)
library(tidyverse)
library(choroplethr)
```


## Wind

Frequency of wind direction and speed (m/s) three days after dicamba application.

```{r include=FALSE, waring=F}
data=read_csv("Weather.csv") %>% 
  drop_na()
str(data)
#data=filter(data)

#Run all this code
plot.windrose <- function(data,
                          spd,
                          dir,
                          spdres = 2,
                          dirres = 22.5,
                          spdmin = 0,
                          spdmax = 6,
                          spdseq = NULL,
                          palette="Oranges",
                          countmax = NA,
                          debug = 0){


  # Look to see what data was passed in to the function
  if (is.numeric(spd) & is.numeric(dir)){
    # assume that we've been given vectors of the speed and direction vectors
    data <- data.frame(spd = spd,
                       dir = dir)
    spd = "spd"
    dir = "dir"
  } else if (exists("data")){
    # Assume that we've been given a data frame, and the name of the speed 
    # and direction columns. This is the format we want for later use.    
  }  

  # Tidy up input data ----
  n.in <- NROW(data)
  dnu <- (is.na(data[[spd]]) | is.na(data[[dir]]))
  data[[spd]][dnu] <- NA
  data[[dir]][dnu] <- NA

  # figure out the wind speed bins ----
  if (missing(spdseq)){
    spdseq <- seq(spdmin,spdmax,spdres)
  } else {
    if (debug >0){
      cat("Using custom speed bins \n")
    }
  }
  # get some information about the number of bins, etc.
  n.spd.seq <- length(spdseq)
  n.colors.in.range <- n.spd.seq - 1

  # create the color map
  spd.colors <- colorRampPalette(brewer.pal(min(max(3,
                                                    n.colors.in.range),
                                                min(9,
                                                    n.colors.in.range)),                                               
                                            palette))(n.colors.in.range)

  if (max(data[[spd]],na.rm = TRUE) > spdmax){    
    spd.breaks <- c(spdseq,
                    max(data[[spd]],na.rm = TRUE))
    spd.labels <- c(paste(c(spdseq[1:n.spd.seq-1]),
                          '-',
                          c(spdseq[2:n.spd.seq])),
                    paste(spdmax,
                          "-",
                          max(data[[spd]],na.rm = TRUE)))
    spd.colors <- c(spd.colors, "grey50")
  } else{
    spd.breaks <- spdseq
    spd.labels <- paste(c(spdseq[1:n.spd.seq-1]),
                        '-',
                        c(spdseq[2:n.spd.seq]))    
  }
  data$spd.binned <- cut(x = data[[spd]],
                         breaks = spd.breaks,
                         labels = spd.labels,
                         ordered_result = TRUE)

  # figure out the wind direction bins
  dir.breaks <- c(-dirres/2,
                  seq(dirres/2, 360-dirres/2, by = dirres),
                  360+dirres/2)  
  dir.labels <- c(paste(360-dirres/2,"-",dirres/2),
                  paste(seq(dirres/2, 360-3*dirres/2, by = dirres),
                        "-",
                        seq(3*dirres/2, 360-dirres/2, by = dirres)),
                  paste(360-dirres/2,"-",dirres/2))
  # assign each wind direction to a bin
  dir.binned <- cut(data[[dir]],
                    breaks = dir.breaks,
                    ordered_result = TRUE)
  levels(dir.binned) <- dir.labels
  data$dir.binned <- dir.binned

  # Run debug if required ----
  if (debug>0){    
    cat(dir.breaks,"\n")
    cat(dir.labels,"\n")
    cat(levels(dir.binned),"\n")

  }  

  # create the plot ----
  p.windrose <- ggplot(data = data,
                       aes(x = dir.binned,
                           fill = spd.binned
                           ,y = (..count..)/sum(..count..)
                           ))+
    geom_bar(size=0.2, color="black") + theme_bw() +
    scale_x_discrete(drop = FALSE,
labels = c("N","","NE","", "E", "", "SE","", 
             "S","", "SW","", "W","","NW","")) +
    coord_polar(start = -((dirres/2)/360) * 2*pi) +
    scale_fill_manual(name = "Wind Speed (m/s)", 
                      values = spd.colors,
                      drop = FALSE) +
    theme(axis.title.x = element_blank(), strip.text.x = element_text(size = 15, colour = "black", face="bold", angle = 0),
          axis.text=element_text(size=14, color="black"), 
        axis.title=element_text(size=18,face="bold"), 
        legend.position="bottom", legend.direction = "horizontal", legend.box = "horizontal", legend.text = element_text(colour="black", size = 12), legend.title = element_text(colour="black", size=12, face="bold"),
  panel.grid.minor = element_blank()) + #facet_wrap(~Day) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    ylab("Frequency")

  # adjust axes if required
  if (!is.na(countmax)){
    p.windrose <- p.windrose +
      ylim(c(0,countmax))
  }

  # print the plot
  print(p.windrose)  

  # return the handle to the wind rose
  return(p.windrose)
}
```


```{r fig.pos='h', echo=FALSE, fig.height= 6, fig.width=8, fig.cap="Wind rose plots demonstrating the average wind frequency (%) and wind speed (m s^1^) grouped in 22.5° of direction (from which the wind is blowing) in Arkansas."}
plot<-plot.windrose(data = data,
              spd = "spd",
              dir = "dir") + 
  ggsave("Wind.pdf", height=6, width=12, dpi=600)
```


```{r fig.pos='h', echo=FALSE, fig.height= 6, fig.width=8, fig.cap="Wind rose plots demonstrating the average wind frequency (%) and wind speed (m s^1^) grouped in 22.5° of direction (from which the wind is blowing) in Arkansas."}
plot<-plot.windrose(data = data,
              spd = "spd",
              dir = "dir") + facet_wrap(~Day) +
  ggsave("Wind2.pdf", height=6, width=12, dpi=300)
```